### ISSUE TITLE
Replacing a bed in the same spot makes /bed work again.

### ISSUE THREAD

**Issue by stapleshotz** [HeroCC/BedHome#1]
BedHome V 2.26
Bukkit version: git-Bukkit-f631379 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

I've set the nobedmode to "b" in the config, and that works fine. When a bed is set and broken, the player is unable to teleport there. However, if you place a bed on the exact spot afterwards, the player is able to teleport there again. 

Is there a way to delete the player's home if the bed is broken?

**Comment by HeroCC** [comment]
I'll look into it, thanks for the suggestion!
