### ISSUE TITLE
java.lang.NoSuchFieldError: LEGACY_BED_BLOCK

### ISSUE THREAD

**Issue by acdsee400** [HeroCC/BedHome#10]
Hi:
When I'm trying to set a bed spawn, bedhome will generate this error, and when I want to teleport, it will simply shows that user's bed does not exist.
Is there any way to fix this issue?

I'm using PaperClip 1.12.2 as server

Here's the full error log:
https://pastebin.com/mY9eHGiS

**Comment by HeroCC** [comment]
Hmm, I thought that was supposed to be backwards compatible. For now, use the older version, and I'll try to get a fixed version out soon.

**Comment by HeroCC** [comment]
Hi @acdsee400, can you try this out? I believe it is fixed, but if you could take a look as well that'd be great. I'm going to try to fix adjacent block detection as well before I publish, but this should work on 1.13 or 1.12. Github won't let me upload a jar, so you'll need to extract this first.

[BedHome-2.30-pre.tar.gz](https://github.com/HeroCC/BedHome/files/2467202/BedHome-2.30-pre.tar.gz)

**Comment by acdsee400** [comment]
Confirmed working on PaperClip 1.12.2
Thanks for the fix.
