### ISSUE TITLE
old bed destroyed, new bed not working

### ISSUE THREAD

**Issue by Rysanlos** [HeroCC/BedHome#12]
Hello, this bug report is a video to be easier to understand the bug:
https://www.youtube.com/watch?v=S-KLQEKdaFo
Thank you if you fix this game breaking bug!

**Comment by HeroCC** [comment]
Thanks for the vid! That helped to explain it. 

When you get the chance, can you try out the jar in this zip? If it works for you I'll upload it to Bukkit. 

[BedHome-2.31.zip](https://github.com/HeroCC/BedHome/files/3180194/BedHome-2.31.zip)

**Comment by Rysanlos** [comment]
I tested the fix you sent, it's working well now, thank you!

**Comment by Rysanlos** [comment]
I have another issue, if I give bedhome.bed permission to a group, it's working well, but the command /bed and description doesn't appear in /help command, it's appear only for admins but not for users with bedhome.bed only. can you fix it? thank you.
Also, there is no documentation about "first-run: true" in config file, what is it?

**Comment by HeroCC** [comment]
Glad the first issue is all set! 
This jar should fix the second issue you described, please try it out and let me know. https://jitpack.io/com/github/HeroCC/BedHome/f04324e2b7/BedHome-f04324e2b7.jar

The first-run line in the config can be safely removed. It currently isn't used in code anywhere, and was added by the old author SuperiorSlime here https://github.com/HeroCC/BedHome/commit/f8fd17cbcb95efb0ae002ca2e0b9e6a5a872f56b#diff-0f1be8eec416e71c28b41efb0544df26R18. I imagine it was going to have some use by him but was never added. I may remove it in the next release, haven't decided yet :sweat_smile:.

**Comment by Rysanlos** [comment]
Thank you the second issue is fixed too, /bed and description are showed in /help now, very nice plugin!
