### ISSUE TITLE
Beds still don't move in 1.13

### ISSUE THREAD

**Issue by Eforen** [HeroCC/BedHome#15]
Issue #12 still not working

**Comment by Eforen** [comment]
The link at the bottom to the patched version is dead

**Comment by HeroCC** [comment]
Sorry you're right, I meant to push up a version to DevBukkit but the issue escaped me. The link worked fine for me though. I'll promote this build to bukkit sometime today or this weekend, if I don't I give you permission to harass me 😉

**Comment by HeroCC** [comment]
Mirror of the 1.31 jar here https://github.com/HeroCC/BedHome/releases/tag/v1.31 (commit b6bde15)

**Comment by HeroCC** [comment]
I just pushed up the 1.31 release to DevBukkit, it should be approved shortly!
