### ISSUE TITLE
Users cannot use /bed, even after permissions are false

### ISSUE THREAD

**Issue by James-Hillmann** [HeroCC/BedHome#16]
What the title says, permissions set to false in config, people on the server cannot use /bed, saying they dont have permission to use it.

**Comment by HeroCC** [comment]
Hi SmallNut, 
To give players permission, you should set the node to true. Setting it to false removes the permission. If that doesn't fix it I'll reopen the ticket and look into it. Hope this helps!

**Comment by HeroCC** [comment]
Ah I understand now! You set permissions to false in config.yml. My bad, I'll reopen this and have it fixed within a few minutes.

**Comment by James-Hillmann** [comment]
Yeah I fixed it a while ago, tysm for commenting.
