### ISSUE TITLE
Bed Mining in the Nether breaks

### ISSUE THREAD

**Issue by Tikkle** [HeroCC/BedHome#20]
[https://youtu.be/1Xj8mBvkZBM](https://youtu.be/1Xj8mBvkZBM)

When bed mining during the Night time ticks of the Minecraft day, the bed will teleport you to it then explode.

**Comment by HeroCC** [comment]
Hi Tikkle, thanks for the report! I'm away from my main development PC right now but I wanted to get a patch out for this ASAP -- I know Bed mining is super useful in 1.16. I just pushed a few commits, could you please test out [this jar](https://jitpack.io/com/github/herocc/bedhome/1d614f3a79/bedhome-1d614f3a79.jar) and let me know how things work? Thanks!
