### ISSUE TITLE
Plugin Cant load on Paper 1.20.1

### ISSUE THREAD

**Issue by BenTheMan69** [HeroCC/BedHome#29]
as the title says, the plugin wont load! i already tried everything with removing other plugins and stuff, but nothing works! it just randomly happened one day after a server restart and wont work anymore.

Heres the Console Log:

09.02 19:34:00 [Server] ERROR Could not load plugin 'BedHome-2.33.jar' in folder 'plugins'
09.02 19:34:00 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bstats/charts/CustomChart
09.02 19:34:00 [Server] INFO at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.20.1.jar:git-Paper-60]
09.02 19:34:00 [Server] INFO at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.1.jar:git-Paper-60]
09.02 19:34:00 [Server] INFO at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.1.jar:git-Paper-60]
09.02 19:34:00 [Server] INFO at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.1.jar:git-Paper-60]
09.02 19:34:00 [Server] INFO at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.1.jar:git-Paper-60]
09.02 19:34:00 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:504) ~[paper-1.20.1.jar:git-Paper-60]
09.02 19:34:00 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.1.jar:git-Paper-60]
09.02 19:34:00 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-60]
09.02 19:34:00 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-60]
09.02 19:34:00 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
09.02 19:34:00 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/bstats/charts/CustomChart
09.02 19:34:00 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
09.02 19:34:00 [Server] INFO at java.lang.Class.forName(Class.java:467) ~[?:?]
09.02 19:34:00 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
09.02 19:34:00 [Server] INFO at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.1.jar:git-Paper-60]
09.02 19:34:00 [Server] INFO ... 9 more
09.02 19:34:00 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bstats.charts.CustomChart
09.02 19:34:00 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
09.02 19:34:00 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
09.02 19:34:00 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
09.02 19:34:00 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
09.02 19:34:00 [Server] INFO at java.lang.Class.forName(Class.java:467) ~[?:?]
09.02 19:34:00 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
09.02 19:34:00 [Server] INFO at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.1.jar:git-Paper-60]
09.02 19:34:00 [Server] INFO ... 9 more

**Comment by HeroCC** [comment]
Ah thanks for the report! Looking into this now...
