### ISSUE TITLE
BedHome plugin not working on 1.13

### ISSUE THREAD

**Issue by fe-ax** [HeroCC/BedHome#7]
Can we get this updated?

**Comment by HeroCC** [comment]
Hi Marco! Thanks for the ticket. Does BedHome print any errors, or simply not function with this update? May I ask what version of BedHome and Spigot you are using?
Thanks!

**Comment by fe-ax** [comment]
Hi HeroCC,

It just keeps saying that I don't have a bed.

This server is running CraftBukkit version git-Spigot-69774b3-a9c796f (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

Sometimes it does seem to work, maybe I don't understand the way it chooses to set my bed as home?


Kind regards,

Marco

**Comment by fe-ax** [comment]
Hi HeroCC,

We've found out it only works with red beds :)


KInd regards,

Marco

**Comment by thedava** [comment]
I can confirm what Marco said. Works with red beds but all other bed variants won't work

**Comment by HeroCC** [comment]
I would like to add some more features into BedHome with multiple colors eventually (ideas anyone?) but for now, this should work on all colors of beds. _Supposedly_ this version is also backwards compatible with pre 1.13, but I don't have a computer with Minecraft on it until next week so I can't test it myself. If you guys wouldn't mind, download this version, and test it out with multiple colored beds. The only major changes I made were changing Block == Bed Detection, as well as getting alternate blocks of the bed (using the new 1.13 part / face api, falling back to iteration loops). 

http://www.mediafire.com/file/g3i3x16hxvc68cz/BedHome-2.29.jar

@MarcoStuurman @thedava Please download and check this jar, if it works I will promote and upload it. Thanks!

**Comment by thedava** [comment]
Tested with a black bed: Seems to work now. Thanks a lot @HeroCC

**Comment by fe-ax** [comment]
It works indeed! Thank you. It would be a super nice feature to have multiple records of beds and location based on their color. So you put a black bed in your mineshaft, a red bed in your house, a white bed at a friends and so on. Commands like /bed blue and /bed (implies red). @HeroCC

**Comment by HeroCC** [comment]
Thanks for testing everyone! I will be posting this to bukkit shortly. If there is enough demand I will look into adding more features related to colors, it may take a bit of work to rewrite the applicable bits of code though. Thumbs up this comment I suppose? 

If anyone has any issues related to this issue (the only one I can guess of right now is possibly overcharging in Vault / not properly detecting the conjoined bed blocks) please make a new issue and I'll look into it right away.

**Comment by HeroCC** [comment]
Posted the new version to bukkit: https://dev.bukkit.org/projects/bedhome/files/2608136

It also has some updates to Metrics and new german translation fixes. No need to update to it if you are working now, but this should fix a few issues relating to unreported metrics so it would make me happy 😃. Plus it's quite a bit smaller as well. Thanks for testing everyone!
